### ISSUE TITLE
cjieba.tag('/') 结果异常，word='', flag='/x'

### ISSUE THREAD

**Issue by yebada** [messense/cjieba-py#5]
```
import jieba     
import jieba.posseg as pseg
import cjieba
jieba.initialize()
list(jieba.cut(line))
```
[u'/', u' ', u'.']
`list(pseg.cut(line))`
[pair(u'/', u'x'), pair(u' ', u'x'), pair(u'.', u'x')]
`list(cjieba.cut(line))`
[u'/', u' ', u'.']
`list(cjieba.tag(line))`
[Tag(word=u'', flag=u'/x'), Tag(word=u' ', flag=u'x'), Tag(word=u'.', flag=u'x')]

这里split 建议改为 rsplit
```
        for item in words:
            word, flag  = item.split('/', 1)
            tags.append(Tag(word, flag))
```

**Comment by messense** [comment]
Thanks for reporting!
